name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
    

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build-action
        with:
            python-version: ${{ matrix.python-version }}
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build-action
        with:
            python-version: ${{ matrix.python-version }}
      - name: Test with unittest
        run: |
          python -m unittest discover -s ./tests -p 'test_*.py'